# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: right_arm
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - ljoint1
    - ljoint2
    - rjoint1
    - rjoint2
    - rjoint3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - ljoint1
    - ljoint2
  gains:
    ljoint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ljoint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - rjoint1
    - rjoint2
    - rjoint3
  gains:
    rjoint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rjoint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rjoint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1